name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job 1: Проверка кода (быстро)
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application (test)
      run: npm run build
      
    - name: Run linting
      run: npm run lint

  # Job 2: Деплой (только если тесты прошли)
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Navigate to project directory
          cd /home/steel/technosolution-steel-frontend
          
          # Pull latest changes
          git pull origin main
          
          # Check if package.json changed to decide if we need npm ci
          if git diff --name-only HEAD~1 HEAD | grep -q "package"; then
            echo "📦 Package files changed, running npm ci..."
            time npm ci
          else
            echo "⚡ No package changes, skipping npm ci..."
          fi
          
          # Build the application
          echo "🔨 Building application..."
          time npm run build
          
          # Restart the application
          echo "🚀 Restarting application..."
          pm2 restart technosolution-steel || pm2 start npm --name "technosolution-steel" -- start
          
          # Show status
          echo "✅ Deployment complete!"
          pm2 status
